from sys import exit

from kojak import cli
from kojak.exceptions import KojakException
from kojak.models import Analyze

from pbr.version import VersionInfo


def main():
    args = cli.argparser()
    version = VersionInfo("kojak")
    if args.version:
        print("kojak v{version}".format(version=version))
        return 0
    filename = args.file
    if not filename:
        return 0

    try:
        analyze = Analyze(filename)
    except KojakException as err:
        print(str(err))
        return 1
    else:
        if not args.summarize:
            for module in analyze.get_modules():
                message = " Module {} ".format(module.name)
                print("-" * len(message))
                print(message)
                print("-" * len(message))
                cli.imports(module)
                cli.classes(module)
        cli.summarize(analyze)
    print("Generated by kojak v{version}".format(version=version))
    return 0


if __name__ == "__main__":
    exit(main())
