from sys import exit

from kojak import cli
from kojak.exceptions import KojakException
from kojak.models import Analyze
from kojak.reports import Report

from pbr.version import VersionInfo


def main():
    args = cli.argparser()
    version = VersionInfo("kojak")
    if args.version:
        print("kojak v{version}".format(version=version))
        return 0
    filename = args.file
    if not filename:
        return 0

    try:
        analyze = Analyze(filename)
    except KojakException as err:
        print(str(err))
        return 1
    else:
        report = Report()
        report.rendering("cli.txt", analyze)
    footer = "Generated by kojak v{version}".format(version=version)
    print("-" * len(footer))
    print(footer)
    print("-" * len(footer))
    return 0


if __name__ == "__main__":
    exit(main())
